-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.departments
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 2 MINVALUE 1 MAXVALUE 3000 CACHE 1 ),
    "position" character varying(50),
    created_date timestamp with time zone,
    active boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(255),
    phone_number character varying(255),
    web_adress character varying(255),
    created_date timestamp with time zone,
    active boolean,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.jobseekers
(
    user_id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    nationality_id character varying(255),
    date_of_birth date,
    created_date timestamp with time zone,
    active boolean,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.staff
(
    user_id integer NOT NULL,
    staff_name character varying(255) NOT NULL,
    created_date timestamp with time zone,
    active boolean,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 4 MINVALUE 1 MAXVALUE 3500 CACHE 1 ),
    email_adress character varying(30) NOT NULL,
    password character varying(30),
    mail_verify boolean,
    active boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.confirm_by_staff
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    staff_id integer NOT NULL,
    confirm_date date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.staff
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.staff
    ADD FOREIGN KEY (user_id)
    REFERENCES public.confirm_by_staff (staff_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.confirm_by_staff (employer_id)
    NOT VALID;

END;